### ISSUE TITLE
Add documentation for how to override Redis settings

### ISSUE THREAD

**Issue by chris-cmsoft** [ContainerSolutions/redis-cluster-operator#11]
It is currently possible to override all of the Redis settings for redis.conf, but this isn't documented anywhere. 

It's a good idea to document these for users.

Currently you can override Redis configuration by specifying it in the CRD under `config:`

```yaml
apiVersion: cache.container-solutions.com/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster-sample
spec:
  masters: 3
  replicasPerMaster: 1
  config: |
    maxmemory 50mb
    maxmemory-policy allkeys-lru
```
